--- #YAML:1.0
name:                Net-IPMessenger
version:             0.07
abstract:            Interface to the IP Messenger Protocol
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
    Class::Accessor::Fast:         0
    Test::More:                    0
    Test::Perl::Critic:            0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Masanori Hara <massa.hara at gmail.com>
