# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Net-IPMessenger
version:      0.05
version_from: lib/Net/IPMessenger.pm
installdirs:  site
requires:
    Class::Accessor::Fast:         0
    Test::More:                    0
    Test::Perl::Critic:            0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
